INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('aaffuso2p@bbc.co.uk', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('aaleksahkin1j@google.ru', 'Chinese acupuncture', 12, 12);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('aaleksahkin1j@google.ru', 'Reflexology', 9, 9);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('aaleksahkin1j@google.ru', 'Shiatsu', 11, 11);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('aantoniat45@techcrunch.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('aantoniat45@techcrunch.com', 'Shiatsu', 1, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ablaise4m@buzzfeed.com', 'Chinese acupuncture', 7, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ablaise4m@buzzfeed.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('abradek@bloomberg.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('abradek@bloomberg.com', 'Reflexology', 8, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adacca3@who.int', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adacca3@who.int', 'Shiatsu', 9, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adetoc25@alexa.com', 'Chinese acupuncture', 10, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adetoc25@alexa.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adevenish5@vkontakte.ru', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adevenish5@vkontakte.ru', 'Reflexology', 2, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adevon27@blogspot.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('adevon27@blogspot.com', 'Shiatsu', 1, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('alillecrap3i@constantcontact.com', 'Chinese acupuncture', 2, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('alillecrap3i@constantcontact.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('amullinl@fc2.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('amullinl@fc2.com', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('anobes26@cdc.gov', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('anobes26@cdc.gov', 'Shiatsu', 4, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('arabier1r@mashable.com', 'Chinese acupuncture', 5, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('arabier1r@mashable.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ascadding2r@51.la', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ascadding2r@51.la', 'Reflexology', 6, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('asmallridge6@t-online.de', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('asmallridge6@t-online.de', 'Shiatsu', 7, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('asneesby58@latimes.com', 'Chinese acupuncture', 8, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('asneesby58@latimes.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('astruis5i@nyu.edu', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('astruis5i@nyu.edu', 'Reflexology', 9, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('awheatcroft56@arstechnica.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('awheatcroft56@arstechnica.com', 'Shiatsu', 9, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bbeaneye@mashable.com', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bbeaneye@mashable.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bbethelo@timesonline.co.uk', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bbethelo@timesonline.co.uk', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bdaviddi4t@wikimedia.org', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bdaviddi4t@wikimedia.org', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bformigli50@aboutads.info', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bformigli50@aboutads.info', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bhanning2o@godaddy.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bhanning2o@godaddy.com', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bjellett2t@surveymonkey.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bjellett2t@surveymonkey.com', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bkleis2e@yandex.ru', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bkleis2e@yandex.ru', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('blankford20@geocities.jp', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('blankford20@geocities.jp', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bmaskelyne3e@fc2.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bmaskelyne3e@fc2.com', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bmytton4n@elegantthemes.com', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('bmytton4n@elegantthemes.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('brobrow3w@trellian.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('brobrow3w@trellian.com', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cabrams3b@unesco.org', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cabrams3b@unesco.org', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cattfield3n@bluehost.com', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cattfield3n@bluehost.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cblackadder3m@vk.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cblackadder3m@vk.com', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cbleaden1v@dmoz.org', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cbleaden1v@dmoz.org', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cchoat2v@hc360.com', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cchoat2v@hc360.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('charbar51@jiathis.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('charbar51@jiathis.com', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('chobbemaa@google.de', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('chobbemaa@google.de', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('clenham2j@boston.com', 'Chinese acupuncture', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('clenham2j@boston.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cmackenny4@pinterest.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cmackenny4@pinterest.com', 'Reflexology', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cmaudlen3r@nifty.com', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cmaudlen3r@nifty.com', 'Shiatsu', 3, 10);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cpetters10@auda.org.au', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cpetters10@auda.org.au', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('crivlin3u@forbes.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('crivlin3u@forbes.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cvorley23@accuweather.com', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('cvorley23@accuweather.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dbugs1z@berkeley.edu', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dbugs1z@berkeley.edu', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ddayly4o@dot.gov', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ddayly4o@dot.gov', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dgokes3z@berkeley.edu', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dgokes3z@berkeley.edu', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dhurne0@nba.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dhurne0@nba.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmarshman36@java.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmarshman36@java.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmerryfield3j@instagram.com', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmerryfield3j@instagram.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmurdy5c@twitter.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmurdy5c@twitter.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmusicka2n@ft.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dmusicka2n@ft.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dnitti4x@bloomberg.com', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dnitti4x@bloomberg.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dredhills3l@blinklist.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dredhills3l@blinklist.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('drekes39@usa.gov', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('drekes39@usa.gov', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dthornewill11@webs.com', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dthornewill11@webs.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dvasilyevski2s@etsy.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dvasilyevski2s@etsy.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dveneurv@de.vu', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dveneurv@de.vu', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dwalhedd53@rakuten.co.jp', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dwalhedd53@rakuten.co.jp', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dwhite4k@shinystat.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('dwhite4k@shinystat.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ebowling4h@addtoany.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ebowling4h@addtoany.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('egambie2d@vkontakte.ru', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('egambie2d@vkontakte.ru', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('eparley41@squarespace.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('eparley41@squarespace.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('epattisson3x@engadget.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('epattisson3x@engadget.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('erezbab@gmail.com', 'Chinese acupuncture', 6, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('erezbab@gmail.com', 'Reflexology', 7, 7);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('erezbab@gmail.com', 'Shiatsu', 9, 9);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('esapauton5h@phpbb.com', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('esapauton5h@phpbb.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('esuter1k@examiner.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('esuter1k@examiner.com', 'Shiatsu', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('etawton43@sbwire.com', 'Chinese acupuncture', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('etawton43@sbwire.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('etinline1@oaic.gov.au', 'Reflexology', 1, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('etinline1@oaic.gov.au', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ewaitland12@kickstarter.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ewaitland12@kickstarter.com', 'Shiatsu', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ewheelwright4s@php.net', 'Chinese acupuncture', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ewheelwright4s@php.net', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ewhiteley44@qq.com', 'Reflexology', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ewhiteley44@qq.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ffollacaro2w@delicious.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ffollacaro2w@delicious.com', 'Shiatsu', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('fhiom4d@webnode.com', 'Chinese acupuncture', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('fhiom4d@webnode.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('fjaine1n@deviantart.com', 'Reflexology', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('fjaine1n@deviantart.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('flaird30@reverbnation.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('flaird30@reverbnation.com', 'Shiatsu', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('fpallaske4r@miibeian.gov.cn', 'Chinese acupuncture', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('fpallaske4r@miibeian.gov.cn', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gatteridge2z@ucoz.com', 'Reflexology', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gatteridge2z@ucoz.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gcosgry4p@jigsy.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gcosgry4p@jigsy.com', 'Shiatsu', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gdacth3h@arstechnica.com', 'Chinese acupuncture', 0, 1);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gdacth3h@arstechnica.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gdiment3f@unc.edu', 'Reflexology', 12, 27);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gdiment3f@unc.edu', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gduesteri@princeton.edu', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gduesteri@princeton.edu', 'Shiatsu', 4, 27);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ghaile29@home.pl', 'Chinese acupuncture', 4, 27);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ghaile29@home.pl', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gmckerley4a@1688.com', 'Reflexology', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gmckerley4a@1688.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gmckinlayp@weather.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gmckinlayp@weather.com', 'Shiatsu', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('griccio37@oaic.gov.au', 'Chinese acupuncture', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('griccio37@oaic.gov.au', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gslucock1c@gov.uk', 'Reflexology', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gslucock1c@gov.uk', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gvedeshkins@pen.io', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('gvedeshkins@pen.io', 'Shiatsu', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hatherton38@utexas.edu', 'Chinese acupuncture', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hatherton38@utexas.edu', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hharpham1p@tripod.com', 'Reflexology', 4, 14);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hharpham1p@tripod.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hpunshonb@archive.org', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hshotboulte1e@drupal.org', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hstanggjertsen2b@dagondesign.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hstockle4u@1und1.de', 'Chinese acupuncture', 3, 9);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hstockle4u@1und1.de', 'Reflexology', 1, 5);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hstockle4u@1und1.de', 'Shiatsu', 3, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('hwathey3t@weebly.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('icoopman4w@army.mil', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('iharvett55@godaddy.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ijuleff5b@spotify.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jangood3g@wikia.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jbootlandt@tamu.edu', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jbromwich1o@gmpg.org', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jbront21@mlb.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jhammerstone1s@sohu.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jlingard49@constantcontact.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jmclugish18@mysql.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jpinching4v@timesonline.co.uk', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jroyse52@noaa.gov', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jscandroot3s@usa.gov', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jschelle2f@tinypic.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('jwincott2c@ibm.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kborn4j@hatena.ne.jp', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kcorbally2g@nhs.uk', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kderx1y@cnet.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kgreenstock3k@amazon.co.uk', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kgregh3q@wp.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kgreydonn@cdc.gov', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kgut59@rakuten.co.jp', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('khowsdenh@edublogs.org', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kjeffery2l@dyndns.org', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('kvoce5e@qq.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lbalcon1d@europa.eu', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lbrabban3c@e-recht24.de', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lclotworthy28@histats.com', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lcutmore4g@nsw.gov.au', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ldugall1m@google.ru', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lharm3d@ovh.net', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lholyardg@list-manage.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('livanyutin46@squidoo.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ljuden5d@prlog.org', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lkorn2y@mapquest.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('llanney8@alexa.com', 'Reflexology', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('llegerz@tuttocitta.it', 'Shiatsu', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lplankr@hubpages.com', 'Chinese acupuncture', 3, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lsporrijc@uol.com.br', 'Reflexology', 3, 13);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('lwoodson4l@storify.com', 'Shiatsu', 3, 13);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mbuckell32@ucsd.edu', 'Chinese acupuncture', 3, 13);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mbunch2u@cmu.edu', 'Reflexology', 3, 13);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mclyburn1b@salon.com', 'Shiatsu', 3, 13);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('meidler2h@columbia.edu', 'Chinese acupuncture', 3, 13);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('membery4q@tuttocitta.it', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mgerin2x@usgs.gov', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mlangdridge13@yahoo.co.jp', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mle1l@spiegel.de', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mpendlebury1i@photobucket.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mrelph31@microsoft.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mrobley47@mail.ru', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mskittle1f@princeton.edu', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mspinozzi9@alexa.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mtireman42@nifty.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('mtrowsdale3o@usatoday.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('nandryushin2q@amazon.de', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('njopke33@walmart.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('nskinglex@surveymonkey.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('nsprakem@indiatimes.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ocordeau4i@reuters.com', 'Reflexology', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ofirazu@post.bgu.ac.il', 'Chinese acupuncture', 4, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ofirazu@post.bgu.ac.il', 'Reflexology', 0, 9);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ofirazu@post.bgu.ac.il', 'Shiatsu', 5, 6);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('opithcock19@ebay.com', 'Shiatsu', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('ovayney@kickstarter.com', 'Chinese acupuncture', 1, 3);
INSERT INTO web_project_g2.membership_card (user_email, treatment_type, totalNumOfTreatmentsRemaining, totalNumOfTreatmentsTotal) VALUES ('paleksidzew@huffingtonpost.com', 'Reflexology', 1, 3);
